---
title: "Math Formula"
author: "Luke"
date: "2022-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

\begin{eqnarray*} aR^{2} &  = &  1-(1-R^{2})\frac{n-1}{n-k-1}\\&  = &  1-(1-.3997)\frac{100-1}{100-3-1}\\&  = &  .3809 \end{eqnarray*}
# one
\begin{eqnarray*} F &  = &  \frac{n-k-1}{k}\frac{R^{2}}{1-R^{2}}\\ &  = &  \left(\frac{100-3-1}{3}\right)\times \left(\frac{0.3997}{1-.3997}\right )=21.307\end{eqnarray*}
# two
A full model: which consists of all the predictors to predict c.gpa by intercept, h.gpa, SAT, and recommd.
A reduced model: obtained by removing the predictors to be tested in the full model.
F=\frac{n-k-1}{p}\frac{R^{2}-R_{0}^{2}}{1-R^{2}}=\left(\frac{100-3-1}{2}\right )\times\frac{.3997-.1226}{1-.3997}=22.157.
# three
\begin{eqnarray*} F &  = &  \frac{n-k-1}{k}\frac{R^{2}}{1-R^{2}}\\ &  = &  \left(\frac{100-3-1}{3}\right)\times \left(\frac{0.3997}{1-.3997}\right )=21.307\end{eqnarray*}

# Four111
$\eta=\sum_{n=1}^{10} n^2$

$\frac{n-k-1}{p}\frac{R^{2}-R_{0}^{2}}{1-R^{2}}=\left(\frac{100-3-1}{2}\right )\times\frac{.3997-.1226}{1-.3997}=22.157$


# Logistic Regression:
$\eta=\log\frac{p}{1-p}$
$\mbox{logit}(p_{i})=\log(\frac{p_{i}}{1-p_{i}})=\eta_i=\beta_{0}+\beta_{1}x_{1i}+\ldots+\beta_{k}x_{ki}$
$p^y (1-p)^{1-y} = p$

## Box
<div class="alert alert-info">
  <strong>Info!</strong> Indicates a neutral informative change or action.
</div>
## Box 2
<div class="alert alert-success">
  <strong>Success!</strong> Indicates a successful or positive action.
</div>

<div class="alert alert-info">
  <strong>Info!</strong> Indicates a neutral informative change or action.
</div>

<div class="alert alert-warning">
  <strong>Warning!</strong> Indicates a warning that might need attention.
</div>

<div class="alert alert-danger">
  <strong>Danger!</strong> Indicates a dangerous or potentially negative action.
</div>
## Box 4
$F=\frac{n-k-1}{p}\frac{R^{2}-R_{0}^{2}}{1-R^{2}}=\left(\frac{100-3-1}{2}\right )\times\frac{.3997-.1226}{1-.3997}=22.157.$
# VV

## R Math Markdown
Greek Letters

$\alpha A$

$\nu N$

$\beta B$

$\xi\Xi$

$\gamma \Gamma$

oO	$o O$ (omicron)

δΔ	$\delta \Delta$

πΠ	$\pi \Pi$

ϵεE	$\epsilon \varepsilon E$

ρϱP	$\rho\varrho P$

ζZ	$\zeta Z \sigma \,\!$	

Σ	$\sigma \Sigma$

ηH	$\eta H$	τT

$\tau T$

θϑΘ	$\theta \vartheta \Theta$

υΥ	$\upsilon \Upsilon$

ιI	$\iota I$	ϕφΦ	

$\phi \varphi \Phi$

κK	$\kappa K$

χX	$\chi X$

λΛ	$\lambda \Lambda$

ψΨ	$\psi \Psi$

μM	$\mu M$

ωΩ	$\omega \Omega$

\begin{eqnarray*} aR^{2} &  = &  1-(1-R^{2})\frac{n-1}{n-k-1}\\&  = &  1-(1-.3997)\frac{100-1}{100-3-1}\\&  = &  .3809 \end{eqnarray*}
Mathematical Notation
Here are some common mathematical things you might use in statistics

x=y	$x = y $

x<y	$x < y $

x>y	$x > y $

x≤y	$x \le y $

x≥y	$x \ge y $

xn	$x^{n}$

xn	$x_{n}$

x¯¯¯	$\overline{x}$

x^	$\hat{x}$

x~	$\tilde{x}$

ab	$\frac{a}{b}$

∂f∂x	$\frac{\partial f}{\partial x}$

∂f∂x	$\displaystyle \frac{\partial f}{\partial x}$

(nk)	$\binom{n}{k}$

x1+x2+⋯+xn	$x_{1} + x_{2} + \cdots + x_{n}$

x1,x2,…,xn	$x_{1}, x_{2}, \dots, x_{n}$

x=⟨x1,x2,…,xn⟩	\mathbf{x} = \langle x_{1}, x_{2}, \dots, x_{n}\rangle$ (\bm from the bm pacakge would be better)

x∈A	$x \in A$

|A|	$|A|$

x∈A	$x \in A$

A⊂B	$x \subset B$

A⊆B	$x \subseteq B$

A∪B	$A \cup B$

A∩B	$A \cap B$

X∼Binom(n,π)	$X \sim {\sf Binom}(n, \pi)$ (sf for “slide font”)

P(X≤x)=pbinom(x,n,π)	$\mathrm{P}(X \le x) = {\tt pbinom}(x, n, \pi)$ (tt for “typewriter type”)

P(A∣B)	$P(A \mid B)$

P(A∣B)	$\mathrm{P}(A \mid B)$ (mathrm for “math roman font”

{1,2,3}	$\{1, 2, 3\}$

sin(x)	$\sin(x)$

log(x)	$\log(x)$

∫ba	$\int_{a}^{b}$

(∫baf(x)dx)	$\left(\int_{a}^{b} f(x) \; dx\right)$

[∫∞−∞f(x)dx]	$\left[\int_{\-infty}^{\infty} f(x) \; dx\right]$

F(x)|ba	$\left. F(x) \right|_{a}^{b}$

∑bx=af(x)	$\sum_{x = a}^{b} f(x)$

∏bx=af(x)	$\prod_{x = a}^{b} f(x)$

limx→∞f(x)	$\lim_{x \to \infty} f(x)$

limx→∞f(x)	$\displaystyle \lim_{x \to \infty} f(x)$
Greek Letters

αA	$\alpha A$	νN	$\nu N$

βB	$\beta B$	ξΞ	$\xi\Xi$

γΓ	$\gamma \Gamma$	oO	$o O$ (omicron)

δΔ	$\delta \Delta$	

πΠ	$\pi \Pi$

ϵεE	$\epsilon \varepsilon E$

ρϱP	$\rho\varrho P$

ζZ	$\zeta Z \sigma \,\!$	

Σ	$\sigma \Sigma$

ηH	$\eta H$

τT	$\tau T$

θϑΘ	$\theta \vartheta \Theta$

υΥ	$\upsilon \Upsilon$

ιI	$\iota I$	

ϕφΦ	$\phi \varphi \Phi$

κK	$\kappa K$

χX	$\chi X$

λΛ	$\lambda \Lambda$

ψΨ	$\psi \Psi$

μM	$\mu M$

ωΩ	$\omega \Omega$

### Equations
\begin{align*}
a & = b \\
X &\sim {\sf Norm}(10, 3) \\
5 & \le 10
\end{align*}